# Generated by Django 3.2.4 on 2021-06-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Blog', '0002_addpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('First_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='profile/')),
            ],
        ),
    ]
