# Generated by Django 3.2.4 on 2021-06-22 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Blog', '0004_rename_first_name_userdata_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('phone', models.IntegerField(null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='profile/')),
            ],
        ),
        migrations.DeleteModel(
            name='userdata',
        ),
    ]
