# Generated by Django 3.2.4 on 2021-06-24 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0008_auto_20210624_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpost',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='addpost',
            name='like',
        ),
        migrations.AddField(
            model_name='addpost',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
