# Generated by Django 3.2.4 on 2021-06-24 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20210624_0455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='postlikes',
        ),
    ]
